### [docker-compose.yml](file:///d:/Laporan-Magang-Bluebird/my-task/develop-parking-space-monitor/docker-compose.yml)

version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TILE38_HOST=tile38
      - TILE38_PORT=9851
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=parking_monitor
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      tile38:
        condition: service_healthy

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=parking_monitor
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "password_encryption=md5"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  tile38:
    image: tile38/tile38:latest
    ports:
      - "9851:9851"
    healthcheck:
      test: ["CMD", "tile38-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: